# -*- coding: utf-8 -*-
"""cli.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HpIdwXYvx0alQu1goatjxk6JmQr_sj9I
"""

# maya/cli.py
import click
from .analyzer import MayaAnalyzer
from .config import MayaConfig

@click.command()
@click.option('--file', required=True, help='Dataset file (csv, xlsx, tsv, json, xml)')
@click.option('--smiles-col', default='SMILES', help='SMILES column name')
@click.option('--id-col', default='ID', help='ID column name')
@click.option('--activities', multiple=True, help='Activity columns')
@click.option('--descriptors', multiple=True, default=['MACCS', 'ECFP', 'druglikeness', 'MAP4'], help='Descriptors to compute')
@click.option('--signaturizer-codes', multiple=True, default=[], help='Signaturizer codes')
@click.option('--output-dir', default='maya_results', help='Output directory')
def maya_cli(file, smiles_col, id_col, activities, descriptors, signaturizer_codes, output_dir):
    """Run MAYA chemical multiverse analysis."""
    config = MayaConfig()
    config.data.update({'id_col': id_col, 'smiles_col': smiles_col, 'activities': list(activities)})
    config.descriptors = list(descriptors)
    config.signaturizer_codes = list(signaturizer_codes)
    config.viz['output_dir'] = output_dir
    analyzer = MayaAnalyzer(config)
    analyzer.run(file)

if __name__ == '__main__':
    maya_cli()
