# -*- coding: utf-8 -*-
"""cli.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I-t4aDfeRxJ9c5AnLWCBiVB5vRD3BIAA
"""

# maya/cli.py
import click
from .analyzer import MayaAnalyzer
from .config import MayaConfig

@click.command()
@click.argument("data_path")
@click.option("--output_dir", default="results", help="Directory to save results")
@click.option("--n_jobs", default=-1, help="Number of parallel jobs")
def main(data_path, output_dir, n_jobs):
    """Run MAYA analysis from command line."""
    config = MayaConfig(data_path=data_path, output_dir=output_dir, n_jobs=n_jobs)
    analyzer = MayaAnalyzer(config)
    analyzer.run()

if __name__ == "__main__":
    main()