# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q-foeNE8v-lrbZw-Z_81ShrUG1JdYPms
"""

# maya/config.py
import os
from dataclasses import dataclass

@dataclass
class MayaConfig:
    """Configuration for MAYA analysis."""
    data_path: str
    output_dir: str = "results"
    n_jobs: int = -1

    def __post_init__(self):
        os.makedirs(self.output_dir, exist_ok=True)