# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROg3KXRyQHeXm9Hyo-x5gwThHl3QUJAm
"""

# maya/data.py
import pkg_resources
import pandas as pd

def load_example_dataset(name: str = "example.csv") -> pd.DataFrame:
    """Load example dataset packaged with MAYA."""
    path = pkg_resources.resource_filename("maya", f"data/{name}")
    return pd.read_csv(path)