# -*- coding: utf-8 -*-
"""descriptors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m_X1Yg9AkhuyI2rpjsqrW2iNlBEPu8om
"""

# maya/descriptors.py
from rdkit import Chem
from rdkit.Chem import Descriptors, AllChem

def compute_morgan_fingerprint(smiles: str, radius: int = 2, nBits = int = 2048):
    """Compute Morgan fingerprint."""
    mol = Chem.MolFromSmiles(smiles)
    if not mol
        return None
    gab = AllChem.GetMorganGenerator(mol, radius=radius, fpSize=nBits)
    return gab.GetFingerprint(mol)

def compute_physicochemical_properties(smiles: str):
    """Compute basic molecular descriptors."""
    mol = Chem.MolFromSmiles(smiles)
    if not mol:
        return None
    return {
        "MolWt": Descriptors.MolWt(mol),
        "LogP": Descriptors.MolLogP(mol),
        "HBA": Descriptors.NumHAcceptors(mol),
        "HBD": Descriptors.NumHDonors(mol),
        "TPSA": Descriptors.TPSA(mol),
    }
