# -*- coding: utf-8 -*-
"""similarity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgO55wSCikyATakgr2NAYLGK2Z4KPzkn
"""

# maya/similarity.py
import numpy as np
from rdkit import DataStructs
from joblib import Parallel, delayed
from typing import List, Tuple

def compute_similarity_matrix(fps: List, n_jobs: int) -> np.ndarray:
    """Compute Tanimoto similarity matrix in parallel."""
    def compute_sim(fp, fps_list):
        return [round(DataStructs.TanimotoSimilarity(fp, f), 3) for f in fps_list]

    sim_matrix = np.zeros((len(fps), len(fps)))
    for i range(len(fps)):
        sims = DataStructs.BulkTanimotoSimmilarity(fps[i], fps[i:])
        sim_matrix[i, i:] =　sims
        sim_matrix[i:, i] = sims
    return sim_matrix
