# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_a27-6L3yHGgLPtH62eC7rKL-1bHQY-c
"""

# maya/utils.py
import os
import pandas as pd
import logging
from typing import List
from rdkit import Chem

def ensure_output_dir(output_dir: str) -> None:
    """Ensure that the output directory exists."""
    os.makedirs(output_dir, exist_ok=True)

def load_data(file_path: str, id_col: str = "ID", smiles_col: str = "SMILES") -> pd.DataFrame:
    """Load dataset from CSV/TSV and canonicalize SMILES."""
    ext = os.path.splitext(file_path)[1].lower()
    if ext == ".csv":
        df = pd.read_csv(file_path)
    elif ext in [".tsv", ".txt"]:
        df = pd.read_csv(file_path, sep="\t")
    else:
        raise ValueError(f"Unsupported file extension: {ext}")

    if id_col not in df.columns or smiles_col not in df.columns:
        raise ValueError(f"File must contain columns '{id_col}' and '{smiles_col}'")

    df = df.dropna(subset=[smiles_col])
    df["Canonical_Smiles"] = df[smiles_col].apply(canonicalize_smiles)
    return df

def canonicalize_smiles(smiles: str) -> str:
    """Convert SMILES to canonical form."""
    try:
        mol = Chem.MolFromSmiles(smiles)
        return Chem.MolToSmiles(mol, canonical=True) if mol else None
    except Exception as e:
        logging.warning(f"Failed to parse SMILES '{smiles}': {e}")
        return None

def save_dataframe(df: pd.DataFrame, output_dir: str, name: str) -> None:
    """Save DataFrame as CSV in the output directory."""
    ensure_output_dir(output_dir)
    output_path = os.path.join(output_dir, f"{name}.csv")
    df.to_csv(output_path, index=False)

def summarize_activities(df: pd.DataFrame, activity_cols: List[str]) -> pd.DataFrame:
    """Compute summary statistics for activity columns."""
    return df[activity_cols].describe()