# -*- coding: utf-8 -*-
"""visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_JqPZfAjLffil21Ce_-7aJYaeX0w7_mb
"""

# maya/visualization.py
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

def plot_similarity_heatmap(sim_matrix, labels, output_path=None):
    """Plot heatmap of similarity matrix."""
    plt.figure(figsize=(10, 8))
    sns.heatmap(sim_matrix, xticklabels=labels, yticklabels=labels, cmap="viridis")
    plt.title("Tanimoto Similarity Heatmap")
    if output_path:
        plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.show()

def plot_scatter(df: pd.DataFrame, x: str, y: str, hue: str = None, output_path=None):
    """Scatter plot for chemical space visualization."""
    plt.figure(figsize=(8, 6))
    sns.scatterplot(data=df, x=x, y=y, hue=hue, alpha=0.7)
    plt.title(f"{x} vs {y}")
    if output_path:
        plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.show()