# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r24A5bFnySbNGHAY0Lpe2wA8s11MMyNZ
"""

# maya/utils.py
import pandas as pd
import numpy as np
import re
from typing import List

def compute_activity_metrics(df: pd.DataFrame, activities: List[str], eval_metric: str, metric_name: str) -> pd.DataFrame:
    """Compute activity metrics and custom evaluation metric."""
    if activities:
        df['mpIC50_value'] = -np.log10(df[activities]).mean(axis=1)
        df['std'] = df[activities].std(axis=1)
        df['norma'] = (df['std'] - df['std'].min()) / (df['std'].max() - df['std'].min() + 1e-6)
        df['normal_deviation'] = df['norma'] * 2 + 9
        df['normal_deviation'] = df['normal_deviation'].fillna(10)
    if eval_metric != 'mpIC50_value':
        cols = re.findall(r'\b\w+\b', eval_metric)
        missing = [c for c in cols if c not in df.columns]
        if missing:
            raise ValueError(f"Missing columns: {missing}")
        df[metric_name] = pd.eval(eval_metric.replace('activities', f"df[{activities}]"), engine='python')
    return df